name: Angular CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Add write permission
    strategy:
      matrix:
        node-version: [18.19.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        npm install
        npm install -g @angular/cli@16
    
    - name: Build
      run: ng build --configuration=production
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/portfolio-v2
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}  # Use default token