name: Angular CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Angular 16 requires Node.js 16.x or higher

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build
      run: npm run build --configuration=production
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: master
        folder: dist/prod-testing  # Update this to match your Angular output path